---
abstract: 'Get, Build and Use SDL libraries'
author:
  - 'Kartik Thakore <KTHAKORE@cpan.org>'
build_requires:
  Archive::Extract: 0
  Archive::Tar: 0
  Archive::Zip: 0
  Digest::SHA: 0
  ExtUtils::CBuilder: 0
  File::Fetch: 0.24
  File::Find: 0
  File::Path: 2.08
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  Module::Build: 0.36
  Text::Patch: 1.4
configure_requires:
  Archive::Extract: 0
  Capture::Tiny: 0
  Digest::SHA: 0
  File::Fetch: 0.24
  File::Find: 0
  File::Path: 2.08
  File::ShareDir: 0
  File::Spec: 0
  File::Which: 0
  Module::Build: 0.36
  Text::Patch: 1.4
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-SDL
provides:
  Alien::SDL:
    file: lib/Alien/SDL.pm
    version: 1.431_2
requires:
  Capture::Tiny: 0
  ExtUtils::CBuilder: 0
  File::ShareDir: 1.00
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
resources:
  bugtracker: http://github.com/PerlGameDev/SDL/issues?labels=Alien-SDL
  license: http://dev.perl.org/licenses/
  repository: http://github.com/PerlGameDev/Alien-SDL
version: 1.431_2
